"""
===========================================================
ForestWatch Zambia
-----------------------------------------------------------
Module: Detection Model

Purpose:
    Stores confirmed or suspected deforestation
    detections generated by the analysis engine.

Responsibilities:
    - Store detected forest changes.
    - Link detections to analysis jobs.
    - Store confidence scores.
    - Support verification workflow.
    - Provide data for alerts and reports.

Author:
    Samuel Bikiloni

Project:
    Web-Based Deforestation Detection and Alert System
    Using Sentinel-2 Imagery in the Copperbelt, Zambia

Version:
    1.0.0
===========================================================
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    DateTime,
    Enum as SqlEnum,
    Float,
    ForeignKey,
    Integer,
    Text,
)
from sqlalchemy.orm import (
    Mapped,
    mapped_column,
    relationship,
)

from app.database.session import Base
from app.models.base_model import AuditMixin
from app.models.enums import DetectionStatus

if TYPE_CHECKING:
    from app.models.alert import Alert
    from app.models.analysis_job import AnalysisJob
    from app.models.forest_area import ForestArea
    from app.models.satellite_image import SatelliteImage
    from app.models.user import User


class Detection(AuditMixin, Base):
    """
    Represents one detected deforestation event.
    """

    # ---------------------------------------------------------
    # Database Table
    # ---------------------------------------------------------
    __tablename__ = "detections"

    # ---------------------------------------------------------
    # Primary Key
    # ---------------------------------------------------------
    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        index=True,
    )

    # ---------------------------------------------------------
    # Foreign Keys
    # ---------------------------------------------------------
    forest_area_id: Mapped[int] = mapped_column(
        ForeignKey("forest_areas.id"),
        nullable=False,
        index=True,
    )

    satellite_image_id: Mapped[int] = mapped_column(
        ForeignKey("satellite_images.id"),
        nullable=False,
        index=True,
    )

    analysis_job_id: Mapped[int] = mapped_column(
        ForeignKey("analysis_jobs.id"),
        nullable=False,
        index=True,
    )

    verified_by: Mapped[int | None] = mapped_column(
        ForeignKey("users.id"),
        nullable=True,
        index=True,
    )

    # ---------------------------------------------------------
    # Detection Results
    # ---------------------------------------------------------
    detected_area_hectares: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Detected area affected.",
    )

    confidence_score: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="AI confidence score.",
    )

    ndvi_before: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    ndvi_after: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    vegetation_loss_percentage: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    status: Mapped[DetectionStatus] = mapped_column(
        SqlEnum(DetectionStatus),
        default=DetectionStatus.PENDING,
        nullable=False,
    )

    verified_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    verification_notes: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    # ---------------------------------------------------------
    # Relationships
    # ---------------------------------------------------------
    forest_area: Mapped["ForestArea"] = relationship(
        "ForestArea",
        back_populates="detections",
        lazy="joined",
    )

    satellite_image: Mapped["SatelliteImage"] = relationship(
        "SatelliteImage",
        back_populates="detections",
        lazy="joined",
    )

    analysis_job: Mapped["AnalysisJob"] = relationship(
        "AnalysisJob",
        back_populates="detections",
        lazy="joined",
    )

    verified_by_user: Mapped["User"] = relationship(
        "User",
        back_populates="verified_detections",
        foreign_keys=[verified_by],
        lazy="joined",
    )

    alerts: Mapped[list["Alert"]] = relationship(
        "Alert",
        back_populates="detection",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    # ---------------------------------------------------------
    # String Representation
    # ---------------------------------------------------------
    def __repr__(self) -> str:
        """
        Return a readable representation of the Detection.
        """

        return (
            f"Detection("
            f"id={self.id}, "
            f"status='{self.status.value}', "
            f"confidence={self.confidence_score:.2f}, "
            f"area={self.detected_area_hectares:.2f} ha)"
        )