"""test

Revision ID: da8e3b0a7357
Revises: 51d7bbc4151b
Create Date: 2026-08-05 20:32:34.636122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da8e3b0a7357'
down_revision: Union[str, Sequence[str], None] = '51d7bbc4151b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False, comment='Forces the user to change password after first login.'))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Last successful login.'))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Date and time the record was last updated.'))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=150),
               comment='Full name of the user.',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='User email address.',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Encrypted user password.',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'FORESTRY_OFFICER', 'RESEARCHER', name='userrole'),
               comment='Role assigned to the user.',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Indicates whether the account is active.',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Date and time the record was created.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Date and time the record was created.',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indicates whether the account is active.',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'FORESTRY_OFFICER', 'RESEARCHER', name='userrole'),
               comment=None,
               existing_comment='Role assigned to the user.',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Encrypted user password.',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='User email address.',
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment='Full name of the user.',
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'must_change_password')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
